[package]
name = "hextobase64"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
base64 = "0.13.0"
clap = "3.1.12"
error-chain = "0.12.4"
data-encoding = "2.3.0"